/* SELF ASSESSMENT
 1. Did I use easy-to-understand meaningful variable names formatted properly (in lowerCamelCase)?
        Mark out of 5: 5
        All variable names clearly indicate their intended value
 2. Did I indent the code appropriately?
        Mark out of 5: 5
        Code indented in appropriate places to make code readable
 3. Did I write the determineStarNumber or determineTriangleNumber function correctly (parameters, return type and function body) and invoke it correctly?
       Mark out of 20: 20
 4. Did I write the isStarNumber function correctly (parameters, return type and function body) and invoke it correctly?
       Mark out of 20: 20
       isStarNumber is passed a triangle number to test and will return a boolean true or false based on whether the number is also a star
 5. Did I calculate and/or check triangle numbers correctly?
       Mark out of 15: 15
       Triangle numbers are generated by the addition of the last triangle number and n, the new number. This will continue to produce triangle number correctly.
 6. Did I loop through all possibilities in the program using system defined constants to determine when to stop?
       Mark out of 10: 10
       Used a sytem defined constant Integer.MAX_VALUE to make sure that the number was still smaller then the max integer value
 7. Does my program compute and print all the correct triangular star numbers?
       Mark out of 20: 20
       The program computed correct values for triangular star numbers until they were bigger then Integer.MAX_INT. This list can be verified at http://oeis.org/A006060
 8. How well did I complete this self-assessment?
        Mark out of 5: 5
        All comments explained properly
 Total Mark out of 100 (Add all the previous marks): 100
*/

public class TriangularStars{
    public static void main(String[] Args){
        int triangleNumber = 0;
        for(int count = 0; triangleNumber >= 0; count++){
            triangleNumber = determineTriangleNumber(count, triangleNumber);
            if(isStarNumber(triangleNumber)){
                System.out.println(triangleNumber);
            }
        }
    }

    public static boolean isStarNumber(int triangleNumber){
        boolean isStarNumber = false;

        long testStar = 0;
        for(int count = 1; testStar < triangleNumber; i++){
            testStar = (6*count*(count-1)) + 1;
            if(testStar > Integer.MAX_VALUE){
                testStar = triangleNumber;
            }
            else if(testStar == triangleNumber){
                isStarNumber = true;
            }
        }
        return isStarNumber;
    }

    public static int determineTriangleNumber(int count, int lastTriangle){
        return count + lastTriangle;
    }
}
